### ISSUE TITLE
Integrate source maps for CSS

### ISSUE THREAD

**Issue by fbugissues** [firebug/firebug#7531]
Originally reported on Google Code with ID 7419
```
What should be implemented/improved?
Source maps support for CSS should be integrated like it's done for JavaScript in issue
5765.

Would be great if someone could provide a proper test case for this.

This is a split of issue 5961.

Sebastian
```

Reported by `sebastianzartner` on 2014-05-01 21:01:44

**Comment by sprat** [comment]
Any progress on this issue? Would love having source maps for CSS, that the only thing we cannot do with Firebug

**Comment by fflorent** [comment]
As it is integrated into the native DevTools, it will be fixed with Firebug 3.0 (aka [firebug.next](https://github.com/firebug/firebug.next)).

I close this issue.

Florent

**Comment by Jany-M** [comment]
Just wondering if there's a release date for Firebug Next?
I can see the last beta was from Dec 2015, so I'm just checking :)

**Comment by janodvarko** [comment]
We decided to integrate Firebug.next directly into devtools. See also: 
https://blog.getfirebug.com/2016/02/08/merging-firebug-into-the-built-in-firefox-developer-tools/

Honza

**Comment by Jany-M** [comment]
I read the post... im still a little confused though. I checked the FF integrated tools (latest FF64bit) and they dont look like anything from the screenshot in the blog post. 
Does it mean that Firebug wont exist anymore once the "merger" will be completed? also, source maps dont really seem to work well on current FF devtools... so basically I dont have anything to work with atm :(

**Comment by janodvarko** [comment]
> I read the post... im still a little confused though. I checked the FF integrated tools (latest FF64bit) and they dont look like anything from the screenshot in the blog post.

The Firebug theme is under construction and should land very soon in Nightly. You might follow bugzilla report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1244054

> Does it mean that Firebug wont exist anymore once the "merger" will be completed? also, source maps dont really seem to work well on current FF devtools... so basically I dont have anything to work with atm :(

Firebug is going to exist, but it won't work on e10s enabled browser. In such case you should switch to Firefox built-in developer tools. Or, if you want Firebug, you need to switch off e10s.

Honza

**Comment by Jany-M** [comment]
Thank you @janodvarko ! Got it now :)
