### ISSUE TITLE
monitor() and debug() commands don't place breakpoints correctly

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug#7907]
STR:
1. Open this page: https://www.mozilla.org/en-US/firefox/nightly/firstrun/?oldversion=38.0
2. Enable Firebug, the Console and the Script panel
3. Enter this command: `debug(Tabzilla.open)`
4. Go to the Script panel and the "Breakpoints" side-panel

The breakpoint is actually set at the line of the function definition, not at the line of the first instruction.

Florent

**Comment by fflorent** [comment]
PR created. Honza, could you review please?

Also note that I work on a similar bug for the DevTools here: https://bugzilla.mozilla.org/show_bug.cgi?id=1164880

Florent

**Comment by janodvarko** [comment]
Merged into the master, closing.

Honza
