### ISSUE TITLE
jQuery-ui dialog() not working when fbug is active

### ISSUE THREAD

**Issue by hiddeneyes02** [firebug/firebug#7914]
<!DOCTYPE html>

    <html>
        <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="jquery_ui.css"/>
        <script src="jquery.js"></script>
        <script src="jquery_ui.js"></script>
        <script>
            $(function () {
                $('#dialog').dialog({
                    autoOpen: false,
                    width: 600,
                    buttons: {
                        "Ok": function () {
                            $(this).dialog('close');
                        },
                        "Cancel": function () {
                            $(this).dialog('close');
                        }
                    }
                });
                $('#opener').click(function (e) {
                    $('#dialog').dialog('open');
                });
            });
        </script>
    </head>
    <body>
        <button id="opener">Open</button>
        <div id="dialog">Dialog box ...</div>
    </body>
</html>

jQuery UI dialog function is working perfectly if fbug is disabled, once it's activated it won't work anymore

Firebug version (number): 2.0.10
Browser version: 38.0.5
Operating system: Win7 64bits

**Comment by fflorent** [comment]
By chance, do you use FireQuery? The FireQuery extension (as currently publised on AMO) is known to prevent scripts from being executed. If so, please, disable it and retry.

Note: We're currently [working on porting](https://github.com/firebug/firequery) FireQuery to Firebug 3.0 and the DevTools.

Florent

**Comment by hiddeneyes02** [comment]
That's it ! Thanks.

**Comment by fflorent** [comment]
Great :)
