### ISSUE TITLE
Complete CSS transform functions

### ISSUE THREAD

**Issue by ManojAMK** [firebug/firebug#7916]
![2015-06-21_12-54-45](https://cloud.githubusercontent.com/assets/11471878/8270849/a6c9c22c-1815-11e5-85b2-0a61731341b6.gif)

I am using the latest Firebug version 2.0.11. I still can't see the [**Perspective**] (https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function) function yet. Is that because it is an experimental feature?

**Comment by fflorent** [comment]
Interesting, I didn't know that CSS property. The document you mention says that it is a CSS property, not a function to be used with transform.

Florent

**Comment by ManojAMK** [comment]
Yes! It is a CSS property with function notation :) In some places it is documented as `property,` while in others it is a `function`. Example: https://dev.opera.com/articles/understanding-3d-transforms/perspective-func.html

**Comment by fflorent** [comment]
Thanks, that's fixed and will be included in an upcoming release.

PS: I renamed your issue, so that's more global to the transform functions.

Florent

**Comment by ManojAMK** [comment]
Thanks for that :+1: Closing this issue.
