### ISSUE TITLE
204 No response

### ISSUE THREAD

**Issue by Hunsu** [firebug/firebug#7926]
In the Net tab firebug show '204 No Response' instead of '204 No Content' for 204 response.

![screenshot from 2015-07-24 14 28 37](https://cloud.githubusercontent.com/assets/6278443/8874386/d24e289c-3210-11e5-8188-983c91ecdcdc.png)

**Comment by SebastianZ** [comment]
The message Firebug displays comes from the server and the server can decide what message to send.

If you have a test case where this is different, then please send it. The issue may be reopened then.

Sebastian
