### ISSUE TITLE
Console tab - cannot check request & response header source when ajax called

### ISSUE THREAD

**Issue by wilzo** [firebug/firebug#7928]
Steps to reproduce

1.    Open Firebug
2.    Enable and switch to the Console panel
3.    put following js in console
xmlhttp = new XMLHttpRequest();
xmlhttp.open("GET", "https://getfirebug.com/", true);
xmlhttp.send();

4.    Click view source beside "Request Headers" or "Response Headers"

Observed result: nothing

Expected result: "Request Headers" or "Response Headers"

**Comment by janodvarko** [comment]
Patch committed, will be fixed in Firebug 2.0.12

Honza
