### ISSUE TITLE
" instead of '

### ISSUE THREAD

**Issue by BubikolRamios** [firebug/firebug#7932]
http://ukmoths.org.uk/thumbnail.php

se page source in firefox & see the same in firebug
sample: 
page source: href='?mode=fam&fam=Noctuidae'
firebug: href="?mode=fam&fam=Noctuidae"

**Comment by fflorent** [comment]
Hello,

Firebug doesn't reflect the source but the DOM tree structure of your HTML. So the replacement of simple quotes to double quotes is normal.

Florent

**Comment by BubikolRamios** [comment]
Thanks for inf.
