### ISSUE TITLE
Errors thrown in page code are silently discarded when code is called from the command line.

### ISSUE THREAD

**Issue by deant** [firebug/firebug#7939]
Consider debugging this simple page (using Firebug v2.0.11 and Firefox v40.0.2 under Window 7 x64):

    <!doctype html>
    <html>
    <head><script>function crash(){ throw new Error("Whoops!") }</script></head>
    <body><input type="button" value="Throw Error" onclick="crash()"></body>
    </html>

If you click the "Throw Error" button, the console logs:

>  Error: Whoops!

...as you would expect.  However, if you type `crash();` into the Firebug command line, no output or result whatsoever appears in the console, when using the default console settings.  The *expected result* is that you should receive the same error as when you clicked the button!

There is similarly no result if you enter
  `try { crash(); } catch(e) { throw e; }`

However, you *do* get the expected error message if you instead enter
   `try { crash(); } catch(e) { throw e.message; }`
...demonstrating that the error is indeed being thrown.

Only if you turn on both of "Show Chrome Errors" and "Show Chrome Messages" does typing `crash();` into the command line yield a tangible result, namely:

> Error: Permission denied to access property "\_\_defineGetter\_\_"

...which probably shouldn't be happening!!!

This isn't confined to deliberately thrown Error objects, either:  I came across this bug while attempting to test edge cases in some complex javascript code by calling various functions explicitly from the Firebug command line.  It seemed to work, but on checking more carefully I noticed some strange things happening, and using the debugger I eventually discovered that execution was just abruptly halting at a particular point in the middle of one of my functions:  The problem was an out-of-range array reference returning `undefined`, where I was expecting a DOM object... but it took me several frustrating hours to discover this, because *I had naturally assumed* that attempting to access properties of an `undefined` variable would automatically log an appropriate error message to the Firebug console!

Worse, had I not looked so closely at the code's actual behaviour, I might have erroneously concluded that the lack of any such error messages meant that the code was actually working correctly (since I was mostly just checking for all-out crashes, on this occasion), and thus ended up releasing buggy code!

I'd expect other developers might similarly be tripped up by this, so I'd say it's a pretty serious bug!

**Comment by fflorent** [comment]
This is already fixed. See https://github.com/firebug/firebug/issues/7923

We're waiting for AMO review (a bit long currently, for some reasons).

Florent

**Comment by deant** [comment]
Ok, sorry for posting a duplicate error report.  But you should perhaps change the title of issue #7923, to indicate that command line errors might get "discarded" or "not appear":  That's what I searched for (and didn't find), before I posted my duplicate error report...

**Comment by fflorent** [comment]
No worry for the duplication :)

> to indicate that command line errors might get "discarded" or "not appear"

Done.

Florent
