### ISSUE TITLE
Incorrect HAR data generation

### ISSUE THREAD

**Issue by suman583** [firebug/firebug#7942]
I am trying to export  a har file using  selenium + firebug+net export.

Selenium version : 2.44
firebug version : 2.0.8
Net Export : 0.7
firefox :33.0

The issue i face is sometimes i get an additional step which appears as first step with  title as that of last step. This happens intermittently.This issue was discussed on forum but its still not resolved.

https://groups.google.com/forum/#!topic/firebug/qydxpGwVcYg

Firebug version (number):33
(Note: Bugs in earlier versions than the latest are unlikely to be fixed.)
Browser version:
Operating system:linux

**Comment by janodvarko** [comment]
NetExport + Firebug combo has been replaced by Firefox + HAR Export Trigger combo
http://www.softwareishard.com/blog/har-export-trigger/

Firefox has native support for HAR export since 41+
Not sure what Firefox version is supported by Selenium though.

Honza
