### ISSUE TITLE
Firebug seems to cause text input issues in FF after period of time

### ISSUE THREAD

**Issue by indextwo** [firebug/firebug#7945]
This has been driving me insane for weeks, and I seem to have narrowed it down to the Firebug add-on running in Firefox.

After a given period and memory usage increase (tests roughly indicate around 60-90 minutes; increase in memory usage of ~100mb), inputting text into fields on certain websites (the two constantly reproducible ones are Google and Facebook) results in half of the characters being omitted, backspace deleting 3 characters at a time, etc.

From what I can determine, this is the case in Google because of its Instant Search / Autocomplete feature, where it tries to pre-empt what you're typing. As a result, if I were to type **This is me typing a sentence at around 30wpm**, the result in Google's search field would be something like **Thss mypnga setncarond3wm**. With Facebook, the input tends to behave well when typing, but if you make a mistake and hit delete, it can delete up to 3 characters at a time (perhaps something to do with auto-drafting or similar functionality). 

These issues do not occur on regular, vanilla inputs that have no autocomplete or other fancy functionality to them.

With regards to memory and time: the only evidence I have for this is that I booted Firefox with only Firebug enabled and recorded the time and memory usage (10:17am, 299,453k; 6 tabs open). At this point, with a fresh restart of Firefox, there were no input issues. I then left it for a while and came back to it (12:05, 452,341k; same 6 tabs) and tried again, and I was suffering the input issues. At this point I disabled Firebug and rebooted Firefox; 12:06, 200,783k usage. It's now 13:34, memory at 377,240k with 9 tabs open, and the issue has not recurred. 

Is this an issue with a memory leak in Firebug, or something else?

For reference:

Windows 7 64-bit SP1
PC Intel 3.7GHz 8gb RAM 1TB SSD
Firefox 40.0.3 running Firebug (and Firebug only in tests)
Firebug v2.0.12

**Comment by niente0** [comment]
Me and my collegue have the same problem. Keystrokes disappears while searching with Google.

Our specs:
Windows 7 64-bit SP1
PC Intel 8-core 3.50Ghz
Ram 32Gb
SSD 256Gb
Firefox 41.0.1 with Firebug v2.0.12

**Comment by indextwo** [comment]
I can also reliably reproduce this in Amazon, where autocomplete is used on the main search field. Again, I can narrow it down directly to Firebug; no other add-ons running, and seems to happen after _some_ period of time.

**Comment by fflorent** [comment]
Hello,

Try again with the Script panel disabled. 
The fact is that the debugger API (used by Firebug and the Firefox DevTools) may slow down an application. I also reproduce the issue with the Fx DevTools too. 

Unfortunately, we probably can't improve that in our side.

Florent

**Comment by indextwo** [comment]
@fflorent Thanks for the update. I've disabled the Script tab as you suggested (almost never used it anyway!) and, as far as I can tell, that seems to have solved the issue! I've only tested sporadically, but it looks good so far (certainly no issues with Google autocomplete at the moment).

**Comment by fflorent** [comment]
Thanks for the feedback!

Florent
