### ISSUE TITLE
Google Maps API and Firebug randomly causes js error

### ISSUE THREAD

**Issue by jamadam** [firebug/firebug#7953]
What steps will reproduce the problem?
1. Go to https://developers.google.com/maps/documentation/javascript/examples/icon-simple
2. Open up Firebug
3. Reload the page

What is the expected output? What do you see instead?

I randomly get following error and map is not shown.

    TypeError: a is undefined
    ...ath.random()>>>0),Ca=0;function Da(a,b,c){return a.call.apply(a.bind,arguments)
    in main.js (line 2, col 643)

It has never happen with built-in firefox developer tool.
This may be related to #7471 but not sure.

**Comment by jamadam** [comment]
sorry for lucking of essential information.

Firefox 41.0.1
Firebug 2.0.12

**Comment by fflorent** [comment]
Maybe related to #7948. Does this build help? https://github.com/firebug/firebug/issues/7948#issuecomment-145633240

Florent

**Comment by jamadam** [comment]
Thanks.
I tried the build and I still get same error.
The frequency is like 1 / 20 or so.

**Comment by jamadam** [comment]
I'm sorry. I could reproduce the exact same error with built-in developer tool so it's not a firebug bug.
