### ISSUE TITLE
Useless information provided

### ISSUE THREAD

**Issue by greencopper** [firebug/firebug#7957]
In the latest stable version of Firebug. In "Net" -> "All", sometimes requests shows as:

Status "Aborted", with no information about what that means. Why, how, reason, etc?

Same issue: http://stackoverflow.com/questions/2766879/http-script-request-aborted-status

Looks like this:

![aborted](https://cloud.githubusercontent.com/assets/1302896/10501274/f4dce460-72df-11e5-93bd-f02e196b10c3.png)

**Comment by fflorent** [comment]
Because there is no information. Please see : 
https://getfirebug.com/wiki/index.php/Net_Panel#Request_List

> Aborted requests 	Requests, which were aborted by the client
