### ISSUE TITLE
Stack traces broken by bug 863089

### ISSUE THREAD

**Issue by simonlindholm** [firebug/firebug#7961]
Presumably. See http://hg.mozilla.org/integration/mozilla-inbound/rev/57714b421d53.

I think we'll need to replace the line
```
            var line = script.getOffsetLine(state.offsets[i]);
```
in content/firebug/console/errorStackTraceObserver.js by
```
            var line = script.getOffsetLocation(state.offsets[i]).lineNumber;
```
for recent Firefox versions.

**Comment by janodvarko** [comment]
@simonlindholm  How can I reproduce the issue?

Honza

**Comment by simonlindholm** [comment]
I don't know, I just saw the commit. Something involving uncaught (or also caught?) exceptions, the Script panel, and the option to show stack traces for errors in the console, probably.
