### ISSUE TITLE
Can't activate "Net/Disable browser cache" in OSX El Capitán

### ISSUE THREAD

**Issue by skyrpex** [firebug/firebug#7967]
The option is there but clicking on it does nothing...

**Comment by fflorent** [comment]
Hello,

Could you be a bit more specific? And what version of Firefox / Firebug do you use?

If I select this option on my machine (Linux Debian / Firefox 42 / Firebug 2.0.13) and refresh some pages, the resources that used to be picked up from the cache (HTTP status = 304) are fetched from the server (status = 200).

Also be careful with this option: it disables the browser cache completely, whether Firebug is open or not, and must slow down your browsing experience if you don't reenable it.

Florent

**Comment by skyrpex** [comment]
Sorry for the lack of information!

Firefox v41.0.2
Firebug v2.0.13
OS: OS X El capitán v10.11.1

The real problem is that the option can't be checked at all. I click it but it keep being unchecked. It works fine in all OSes but OSX El Capitán.

**Comment by skyrpex** [comment]
Looks like its was Firefox's fault. It works now.

Firefox v42.0
Firebug v2.0.13
OS: OS X El capitán v10.11.1

**Comment by fflorent** [comment]
Thanks for the feedback @skyrpex 

Florent
