### ISSUE TITLE
Get Involved: "Firebug Issue Tracker" links to Google Code (read-only)

### ISSUE THREAD

**Issue by Chealer** [firebug/firebug#7976]
The "Firebug Issue Tracker" link on http://getfirebug.com/getinvolved points to https://code.google.com/p/fbug/issues/list

There is a "READ-ONLY: This project has been archived. For more information see this post. " mention at the top which brings here ( https://github.com/firebug/firebug/issues ).

**Comment by janodvarko** [comment]
Should be fixed now, please verify.

Thanks for the report!

Honza
