### ISSUE TITLE
Installing firebug from getfirebug.com

### ISSUE THREAD

**Issue by rahulkapoor90** [firebug/firebug#7986]
I recently went to getfirebug.com and wanted to reinstall add-on. the problem is people having poor internet connectivity will find it difficult to first redirect to downloads page and then from there to firefox add-on website.

TLDR; can you provide ability to start downloading add-on from the same getfirebug.com only like everyone else do.

**Comment by stof** [comment]
due to the requirements for addons to be signed to be used in Firefox now, this is not easy.
