### ISSUE TITLE
Firebug 2 doesn't work with multiprocess Firefox(e10s)

### ISSUE THREAD

**Issue by pvegetah** [firebug/firebug#7989]
Yesterday I encounter this on my Firebug. 
![firefox-issue](https://cloud.githubusercontent.com/assets/14344909/12804011/10b7b55a-cb2a-11e5-9eac-c6105c7bcbef.jpg)

When I select the Disable e10s and Restart it will restart but still have the problem and when I select the upgrade and restart it will prompt this

![firefox-issue2](https://cloud.githubusercontent.com/assets/14344909/12804078/aad3239a-cb2a-11e5-95d2-814cfbf4dac8.jpg)

So when I go to the page and download some either alpha version or beta version of firebug 3 it will recognize as unverified addon just like this

![firefox-issue3](https://cloud.githubusercontent.com/assets/14344909/12804103/e91f9f20-cb2a-11e5-9c5c-228ee0f9d58a.jpg)

Is there a solution for this? Thank you

**Comment by fflorent** [comment]
Hello,

As the message says, you should upgrade to Firebug 3.0. But Firebug fails to update by his own.

What is your Firebug 2.0 version please (the latest being 2.0.14) ?

Florent

**Comment by pvegetah** [comment]
My firebug version is Firebug 2.0.14. I already reinstall the firebug latest version but still the problem.

**Comment by janodvarko** [comment]
The xpi (FB3) is not signed

Does it help if you set the following pref to false and try again?

xpinstall.signatures.required

Honza

**Comment by pvegetah** [comment]
@janodvarko I already set the pref to false but then and then the problem still exist.

**Comment by pvegetah** [comment]
Thanks firebug you already solve my problem.
