### ISSUE TITLE
Firebug disable dns

### ISSUE THREAD

**Issue by chipx0r** [firebug/firebug#7992]
Yesterday my firebug auto-update (the report register the update in the configuration history with yesterday date), and today in the morning I was unable to browse in firefox outside my LAN space 192.168.X.X
I'm sure the problem was firebug, because I generated another profile in FF, and I was able to browse internet. I spent time troubleshooting my FF profile and the last register before malfunction was the firebug update.
Later, I rolled back to my old profile, REMOVED firebug; and I was able to browse again. Couple hours later, I reinstalled again firebug and everything is working fine again. 
I'm not sure if this could be classified as a FF-mistery or there is something wrong with the last update

**Comment by chipx0r** [comment]
Sorry about this, It was the FF update 44 itself.

**Comment by todeale** [comment]
Ouff!
