### ISSUE TITLE
Migration message to new Firefox devtools is way too negative

### ISSUE THREAD

**Issue by jnachtigall** [firebug/firebug#7998]
I've read https://blog.getfirebug.com/2016/02/08/merging-firebug-into-the-built-in-firefox-developer-tools/

![notification](https://cloud.githubusercontent.com/assets/3307404/13701076/5e098596-e785-11e5-8c2e-aaedbc444012.png)

To my ears the migration message, especially the 1st sentence, is way too negative. It sounds like something is broken, _does not work_ anymore and to get it back you need to _disable _something. 

I think it is great the Firebug has been integrated into the devtools: Many new great features and tools! The migraton message should be positive and make curious to try out.

Here's a proposal:

> The next Firebug version has been integrated into the built-in Firefox Developer Tools. It comes with new and great features like XXX, YYY, ZZZ and many more. Existing Firebug features have been ported into the new tools. So go ahead and check it out.
> 
> [Learn more...]
> 
> [ ] Do not display this message again
> 
> [Open Firefox Developer Tools]

I'd leave the e10s aspect out of it. Many users do not know what it is. And it makes it sound like something is really broken. I'd just go to explain about e10s in the "Learn more" article.

**Comment by jnachtigall** [comment]
Just a word on the motivation: I work as a web dev. Most of my colleagues use Chrome (75%), Firebug is about (20%) the ff devtools is maybe (5%). I think if the migration message sounds like something is broken (instead of something new and shiny coming) then some people will rather take this as a motivation to switch to chrome than the ff devtools.

**Comment by janodvarko** [comment]
Good point, I like the suggestion.

See the attached screenshot showing how it looks like now.

![migration-message](https://cloud.githubusercontent.com/assets/37785/13924865/4a92c500-ef86-11e5-9f75-dab1b0e84b97.png)

Does that look ok?

Honza

**Comment by jnachtigall** [comment]
Looks good to me. Thx! 

--
Sorry for shortness, mail was sent from my smartphone.



Am 21. März 2016 18:00:20 OEZ, schrieb Jan Odvarko <notifications@github.com>:

**Comment by janodvarko** [comment]
Yet tweaking the message a bit.

![msg](https://cloud.githubusercontent.com/assets/37785/13993300/10e495fe-f120-11e5-82b7-0d17be1db277.png)


Honza
