### ISSUE TITLE
Firebug doesn't work on non-E10S Nightly

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug#8000]
Some deprecated APIs prevent Firebug from working (reported by Shelburn)

**Comment by janodvarko** [comment]
https://github.com/firebug/firebug/commit/3bcc4d9b19e8ea0e23085cab7b9fbb3f2d29dcc6
https://github.com/firebug/firebug/commit/8d08a9fe6be130a88b783d7ccc2758d9d08d3f62

I believe it's fixed now, thanks for the report Florent!

Let me know if you still experience a problem.

Honza
