### ISSUE TITLE
Firebug icon not showing in Address bar in Firefox browser 

### ISSUE THREAD

**Issue by joydeepint** [firebug/firebug#8004]
Hi,
Firebug icon not showing in Address bar in Firefox broswser, even I reinstall many times but not showing at all. Also do right click -> Inspect Element (Q) but showing Firefox default Inspect Tool.  I am using Firefox 31.0 Mozilla Firefox for Ubuntu canonical - 1.0. 
Thanks
Joy

**Comment by bytefather** [comment]
Hi
Same problem with Linux Mint LMDE (3.11-2-686-pae #1 SMP Debian 3.11.8-1 (2013-11-13) i686 GNU/Linux) and Firefox v35. 
After update to new version (2.0.15) Firebug stopped working. 
Best regards and thanks for your great tool, 
ByteFather

**Comment by joydeepint** [comment]
Hi,
I have resolved it by uninstall completely and then install again.

**Comment by janodvarko** [comment]
Did you test with Firefox 35?

Honza

**Comment by joydeepint** [comment]
No actually, I am using Firefox 45.0.1

**Comment by janodvarko** [comment]
OK, I see. There are threads on newsgroups saying that Firebug isn't working in Firefox 35/30

https://groups.google.com/forum/#!topic/firebug/DK_bB-2qnFQ
https://groups.google.com/forum/#!topic/firebug/G4seKYNmRrw

I'll use this report to fix it.

Honza

**Comment by janodvarko** [comment]
Here is a test build with patch for Firefox 30/35 included:
http://janodvarko.cz/temp/firebug/firebug-2.0.15.8004.xpi

Can anyone verify that it works now?

Honza

**Comment by bytefather** [comment]
Hi Janodvaro, 
It seems to be working now, thanks. 
Best Regards, 
ByteFather

**Comment by guerda** [comment]
Hi @janodvarko !

I had the same problem with Firefox ESR 31.8.0 on Windows 7, 64 bit. Even with a clean profile, the problem persisted. Especially the F12 key was bound to the Firefox inspector, instead of Firebug.
I now used your test build from 5 days ago and Firebug opens again.
Thanks for the patch!

**Comment by janodvarko** [comment]
Thanks for the verification!
Honza
