### ISSUE TITLE
Some flexbox CSS autocompletion properties not working

### ISSUE THREAD

**Issue by performatric** [firebug/firebug#8015]
I have tested with these properties (align-items, justify-content, align-self, justify-self)
Firebug suggests only "unset", "inherit" and "initial" values.
Where is the "flex-start", "flex-end", "space-between"... ???

Previously it works!

Now I'm using Firefox: 45 - 46
Firebug: 2.0.16

Sorry my english! :)

**Comment by yairEO** [comment]
for me also, and many other autocompletion for other properties aren't there anymore! had to go back to older Firebug and older Firefox to resolve this, but still I have issues where things aren't nearly as good as before. very odd. on other computers also.

**Comment by performatric** [comment]
has been fixed
