### ISSUE TITLE
Computed side panel is not showing CSS links (to CSS files), no CSS categories

### ISSUE THREAD

**Issue by tkutlic** [firebug/firebug#8020]
Hi,
I 'm sending  picture of the current state of side panel:
https://drive.google.com/open?id=0BxXPgm5QBUDtUVp1cm1HQzNTcHM

Only category "Other" is present
Please tell how to fix it (or give up ...if this is not a bug but a feature :-D)

The steps I have taken so far are:

I uninstalled FF x86, wiped all files and data thoroughly
Re-installed FFx86
Installed Firebug

Thoroughly uninstalled FF again and installed 64-bit version
Again installed Firebug

I followed all the steps on this page:
https://getfirebug.com/wiki/index.php/I_found_a_Firebug_Bug!

annotations.json is empty
breakpoints.json is empty

I am sending prefs.js:
https://drive.google.com/open?id=0BxXPgm5QBUDtMDZWVUloTm4yQU0

Can the panel look like this again ?:
https://getfirebug.com/wiki/index.php/Computed_Side_Panel

Addition:
OS Win 7 64 bit

Tnx
Toni

**Comment by SebastianZ** [comment]
See issue #8018.

Sebastian
