### ISSUE TITLE
PrettyPrint doesn't parse function lambda-style

### ISSUE THREAD

**Issue by Baud21** [firebug/firebug#8025]
This code:
`var test = () => {}`
is formatted into:
```
var test = () = > {
}
```
Note the space between `=` and `>` make doesn't work.

**Comment by simonlindholm** [comment]
This is actually a bug in the built-in devtools, which Firebug depends on: https://bugzilla.mozilla.org/show_bug.cgi?id=951622 I imagine opening a simple PR as described in comment 17 there will speed fixing this up a bit, if you're interested.
