### ISSUE TITLE
Mark as e10s compatible

### ISSUE THREAD

**Issue by janodvarko** [firebug/firebug#8030]
Firebug xpi should be marked as e10s compatible. Firebug itself doesn't work with e10s, but migration UI that helps users to shift to built-in Firefox DevTools must work.

Honza

**Comment by Chealer** [comment]
Thank you Honza, for your work on this issue and on Firebug in general.

I could not understand the 2.0.18 release notes, which contain:

> It does *not* mean that Firebug itself supports multi-process browser.

I suggest to replace that with:

> When opened in a multi-process Firefox, Firebug's tools cannot be used. Firebug will then only assist the user with migration to Firefox's built-in tools.

**Comment by janodvarko** [comment]
@Chealer: done, thanks!

Honza
