### ISSUE TITLE
Script tab not work since update ff to 50

### ISSUE THREAD

**Issue by Abdipour** [firebug/firebug#8057]
hi,
since ff update to 50, script tab show "No Javascript on this page" in any webpage. 
"Clear Activation List" not solved this issue...

**Comment by arielmorry** [comment]
+1

**Comment by sdavidg** [comment]
Same bug here: https://github.com/firebug/firebug/issues/8040

**Comment by klcockerill** [comment]
I am also experiencing the same problem. I have tried "Clear Activation List", also manually deleted the annotations.json & breakpoints.json, as well as disabling all other add-ons all without any success. I am running Firebug 2.01.8 with Firefox 50.0 on Windows 7 Enterprise Service Pack 1 with all the latest updates.

**Comment by blawson75** [comment]
+1

**Comment by allgorod** [comment]
+1

**Comment by SebastianZ** [comment]
I am experiencing the same on Windows 10.

Though note that Firebug is [not actively developed anymore](https://blog.getfirebug.com/2016/06/07/unifying-firebug-firefox-devtools/). The Firebug Working Group suggests to switch to the [Firefox DevTools](https://developer.mozilla.org/en-US/docs/Tools) instead, which now have a Firebug theme.

I was asked in [bug 991806 comment 15](https://bugzilla.mozilla.org/show_bug.cgi?id=991806#c15) to ask everyone to post the features Firebug had and you're missing in the DevTools to https://groups.google.com/forum/#!topic/firebug/Q6eyvGt6hyI/discussion.

Sebastian

**Comment by EToniolo** [comment]
+1

**Comment by Cesar-Ofi** [comment]
+1

**Comment by bkuehhnle** [comment]
+1

**Comment by Abdipour** [comment]
The Firebug extension isn't being developed or maintained any longer. We invite you to use the Firefox built-in DevTools instead.

https://blog.getfirebug.com/2016/02/08/merging-firebug-into-the-built-in-firefox-developer-tools/

**Comment by valedp88** [comment]
+1
