### ISSUE TITLE
Are you kidding me?

### ISSUE THREAD

**Issue by dehghani-mehdi** [firebug/firebug#8058]
Hi,

There is tons of issues & looks like you didn't even check them. you said long time ago, you'll `Merging Firebug into the built-in Firefox Developer Tools`, but you just added `Firebug theme`, please!!, we don't care about theme, we care about useful features than `Firebug` have.

If you don't have plan to develop Firebug anymore, just say it. you know, __I love Firebug__, but now I'm disappointed.

**Comment by fsworld009** [comment]
According to the README they just updated, firebug is not maintained anymore. Please switch to built-in developer tool. The two already merged since Firefox 49 according to [this blog post](https://blog.getfirebug.com/2016/06/07/unifying-firebug-firefox-devtools/)

**Comment by dehghani-mehdi** [comment]
@fsworld009 I'm using Firefox dev tools (since I saw Firebug team behavior), I like Firebug & I just want to know what the team doing & what is their REAL plan for Firebug.

**Comment by SebastianZ** [comment]
The blog post didn't clearly state it, though Firebug is discontinued. The team has split up, the former team leader Jan "Honza" Odvarko is working on the Firefox DevTools now. I [already left the team in 2014](https://groups.google.com/forum/#!topic/firebug-working-group/6PulwrKtmtE) and am now contributing to MDN instead (as a volunteer), though I'm currently trying to help Firebug users migrate to the Firefox DevTools by writing a [migration guide](https://developer.mozilla.org/en-US/docs/Tools/Migrating_from_Firebug).

Also, I [was asked in bug 991806](https://bugzilla.mozilla.org/show_bug.cgi?id=991806#c15) to ask Firebug users what they are missing most in the Firefox DevTools. So, please post here:

https://groups.google.com/forum/#!topic/firebug/Q6eyvGt6hyI/discussion

**Please only post constructive critics there!**

Sebastian

**Comment by dehghani-mehdi** [comment]
@SebastianZ first thank you for all your works for Firebug. really great tools.

I read almost all your linked articles/pages.
As Firebug user/fan, also Firefox user/fan, I asked to focus on `features & behavior` instead of `theme` . since I switched to `Firefox Dev tools`, I never used `Firebug theme`, because I don't care about theme, I want to work/debug the code using dev console.
I know there is not right place to saying this, but I think Firefox team should stared adding features to Dev tools long time ago, before putting users to this situation. (by situation I mean no Firebug & no Firebug features/behavior inside Firefox dev tools). of course there is some great features inside Dev tools, but not enough, because we use Firebug for long time.

Anyway thanks & please keep helping Firefox.

**Comment by SebastianZ** [comment]
> I know there is not right place to saying this, but I think Firefox team should stared adding features to Dev tools long time ago, before putting users to this situation. (by situation I mean no Firebug & no Firebug features/behavior inside Firefox dev tools).

I agree with you. Unfortunately, the DevTools team couldn't prioritize all Firebug features, because they are also working on other parts, which makes the transition for Firebug users somewhat rough.

Though while some Firebug features are still missing or not working as good as in Firebug, the DevTools offer some other cool features. See [their release notes](https://developer.mozilla.org/en-US/docs/Tools/Release_notes) for some of them.

Sebastian
