### ISSUE TITLE
Doesn't work properly in Firefox 51.0.1

### ISSUE THREAD

**Issue by matiosfree** [firebug/firebug#8070]
Hey everyone.

Plugin doesn't work properly in Firefox 51.0.1. (2 days ago everything was good). When I'm trying to open  firebug panel, I see default FF devtools instead of. And plugin is switched off. The same behavior is via context menu "Inspect in Firebug" and via clicking to plugin's icon.

- Win7
- Firefox 51.0.1
- Firebug 2.0.18

**Comment by andyrooc** [comment]
From: http://getfirebug.com/

"The Firebug extension isn't being developed or maintained any longer. We invite you to use the Firefox DevTools instead, which ship with Firebug.next "

It's true the menu option is still there, but it no longer opens Firebug.

**Comment by matiosfree** [comment]
oh... really... but "Console" tab is uncomfortable in Firefox DevTools. There is no multi-line mode for console... Oh, thanks for explanation.

**Comment by SanyaTolok** [comment]
And what to do with FirePath it doesn't work too, because firebug required for it.

**Comment by Sogl** [comment]
Sad but true... Now my FirePHP extension also doesn't work. 
I really don't like how FF DevTools look and feel.

**Comment by trupka** [comment]
Some [bad things happened](https://addons.mozilla.org/en-US/firefox/addon/firebug/reviews/) to firebug recently. Version integrated in FF 51 is, mildly said, useless.
However, there is a way to enable old Firebug plugin:

**To enable old Firebug**
In address enter about:config, find
browser.tabs.remote.autostart set it false
browser.tabs.remote.autostart.1 set it false
browser.tabs.remote.autostart.2 set it false

**Comment by craigcarnell** [comment]
Please bring back the old firebug, firefox dev tools suck

**Comment by veso266** [comment]
yea I had to install Firefox 49 because of this 

I love firebug so much and I've always hated firefox DevTools (javascript console is usless in them)
