### ISSUE TITLE
!important in CSS not show up

### ISSUE THREAD

**Issue by digital666** [firebug/firebug#8086]
When edititing/writing CSS the "!important" will not show up. Self implemented not and already existing neather. When coping css from firebug it will not apear also. Thanks a lot firebug is a Great tool.
firebug 2.0.19
firefox 53.0 (64-Bit)

**Comment by anonymuos1** [comment]
Same here... where is !important??

**Comment by agb** [comment]
I show the same problem.

**Comment by trishah** [comment]
Same here.  I can add "!important" to the CSS in FireBug and it does apply to effect the web page I'm on, but the actual text "!important" disappears from FireBug and can not be copied to the stylesheet. VERY annoying.

**Comment by arianaquila** [comment]
I have the same problem

**Comment by SebastianZ** [comment]
If you didn't notice, Firebug is [officially discontinued for quite some time](https://hacks.mozilla.org/2016/12/firebug-lives-on-in-firefox-devtools/) in favor of the Firefox built-in DevTools.

Sebastian
